language: php

php:
  - 7.1
  - 7.2
  - 7.3

services:
  - mysql

install:
  - wget http://selenium-release.storage.googleapis.com/2.42/selenium-server-standalone-2.42.2.jar
  - composer install

before_script:
  - export APPLICATION_ENV=travis
  - echo "CREATE DATABASE bone_db; USE mysql;\nUPDATE user SET authentication_string=PASSWORD('drinkgrog') WHERE user='travis';\nFLUSH PRIVILEGES;\n " | mysql -u root

script:
  - php vendor/bin/codecept run unit --coverage-xml --env travis -vvv

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover tests/_output/coverage.xml

notifications:
  irc: "irc.freenode.org#bonemvc"
