language: php

php:
  - 5.6
  - 7.0
  - 7.1



branches:
  except:
    - gh-pages



install:
  - wget http://selenium-release.storage.googleapis.com/2.42/selenium-server-standalone-2.42.2.jar
  - composer install


before_script:
  - sudo chmod 777 /etc/hosts
  - echo 127.0.0.1 bone > /etc/hosts
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 5
  - java -jar selenium-server-standalone-2.42.2.jar -port 4444 &
  - echo "CREATE DATABASE bone_db; USE mysql;\nUPDATE user SET password=PASSWORD('drinkgrog') WHERE user='travis';\nFLUSH PRIVILEGES;\n " | mysql -u root
  - nohup php -S bone:8000 public/index.php &

script:
  - php vendor/bin/codecept run unit --coverage-xml --env travis -vvv

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover tests/_output/coverage.xml

notifications:
  irc: "irc.freenode.org#bonemvc"
