language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

matrix:
  allow_failures:
    - php: hhvm

branches:
  except:
    - gh-pages

services:
  - mongodb
  - rabbitmq

install:
  - wget http://selenium-release.storage.googleapis.com/2.42/selenium-server-standalone-2.42.2.jar
  - composer global require "fxp/composer-asset-plugin:1.0.0-beta2"
  - composer install
  # Queue (Beanstalkd)
  - sudo apt-get update -qq
  - sudo apt-get install -qq beanstalkd


before_script:
  - beanstalkd -d -l 127.0.0.1 -p 11300
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - echo "extension = mongo.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - sleep 5
  - java -jar selenium-server-standalone-2.42.2.jar -port 4444 &
  - "mysql -e 'create database codeception_test;'"
  - psql -c 'create database codeception_test;' -U postgres
  - php -S localhost:8000 -t tests/data/app &
  - php -S localhost:8010 -t tests/data &
  - "mysql -e 'CREATE DATABASE forum;'"
  - cat frameworks-phalcon/schemas/forum.sql | mysql forum

script:
  - php vendor/bin/codecept run  # self tests